#!/bin/bash
# Theme hook: Update Waybar styling

CRUZALEX_DIR="${CRUZALEX_DIR:-$HOME/.config/cruzalex}"
THEME_DIR="${THEME_DIR:-$CRUZALEX_DIR/current}"
WAYBAR_CONFIG="$HOME/.config/waybar"

# Link theme CSS if it exists
if [ -f "$THEME_DIR/waybar/style.css" ]; then
    ln -sf "$THEME_DIR/waybar/style.css" "$WAYBAR_CONFIG/theme.css"
elif [ -f "$THEME_DIR/waybar.css" ]; then
    ln -sf "$THEME_DIR/waybar.css" "$WAYBAR_CONFIG/theme.css"
fi

# Generate CSS variables from colors.toml
generate_css_vars() {
    local colors_file="$THEME_DIR/colors.toml"
    local output_file="$WAYBAR_CONFIG/colors.css"

    if [ ! -f "$colors_file" ]; then
        return
    fi

    mkdir -p "$WAYBAR_CONFIG"

    echo "/* Auto-generated by cruzalex-theme-set */" > "$output_file"
    echo "@define-color background $(grep '^background *=' "$colors_file" | head -1 | cut -d'"' -f2);" >> "$output_file"
    echo "@define-color foreground $(grep '^foreground *=' "$colors_file" | head -1 | cut -d'"' -f2);" >> "$output_file"
    echo "@define-color accent $(grep '^accent *=' "$colors_file" | head -1 | cut -d'"' -f2);" >> "$output_file"

    # Add ANSI colors - use exact match with = to avoid color1 matching color10
    for i in {0..15}; do
        local color=$(grep "^color$i *=" "$colors_file" | head -1 | cut -d'"' -f2)
        if [ -n "$color" ]; then
            echo "@define-color color$i $color;" >> "$output_file"
        fi
    done
}

generate_css_vars

# Restart Waybar if running
if pgrep -x "waybar" > /dev/null; then
    pkill -SIGUSR2 waybar 2>/dev/null || killall -SIGUSR2 waybar 2>/dev/null || true
fi
