#!/bin/bash
# Theme hook: Update Mako notification daemon

CRUZALEX_DIR="${CRUZALEX_DIR:-$HOME/.config/cruzalex}"
THEME_DIR="${THEME_DIR:-$CRUZALEX_DIR/current}"
MAKO_CONFIG="$HOME/.config/mako"

# Generate mako config from colors.toml
generate_mako_config() {
    local colors_file="$THEME_DIR/colors.toml"
    local output_file="$MAKO_CONFIG/theme"

    mkdir -p "$MAKO_CONFIG"

    if [ ! -f "$colors_file" ]; then
        return
    fi

    local bg=$(grep '^background' "$colors_file" | cut -d'"' -f2)
    local fg=$(grep '^foreground' "$colors_file" | cut -d'"' -f2)
    local accent=$(grep '^accent' "$colors_file" | cut -d'"' -f2)

    # Write theme config
    cat > "$output_file" << EOF
# Auto-generated by cruzalex-theme-set
background-color=${bg}ee
text-color=${fg}
border-color=${accent}
progress-color=over ${accent}
EOF
}

# Use theme-provided config if available
if [ -f "$THEME_DIR/mako/config" ]; then
    mkdir -p "$MAKO_CONFIG"
    ln -sf "$THEME_DIR/mako/config" "$MAKO_CONFIG/theme"
else
    generate_mako_config
fi

# Reload mako
if pgrep -x "mako" > /dev/null; then
    makoctl reload 2>/dev/null || true
fi
