#!/bin/bash
# Theme hook: Update Neovim colorscheme
# Uses file-based signaling instead of socket IPC to avoid hangs

CRUZALEX_DIR="${CRUZALEX_DIR:-$HOME/.config/cruzalex}"
THEME_DIR="${THEME_DIR:-$CRUZALEX_DIR/current}"
NVIM_CONFIG="$HOME/.config/nvim"
LAZYVIM_PLUGINS="$NVIM_CONFIG/lua/plugins"

# Check if theme provides a neovim.lua plugin file (Omarchy format)
NEOVIM_LUA="$THEME_DIR/neovim.lua"
if [ -f "$NEOVIM_LUA" ]; then
    # Symlink the theme's neovim.lua to LazyVim plugins directory
    mkdir -p "$LAZYVIM_PLUGINS"
    ln -sf "$NEOVIM_LUA" "$LAZYVIM_PLUGINS/cruzalex-theme.lua"

    # Extract colorscheme name from the lua file if possible
    NVIM_COLORSCHEME=$(grep -oP "vim\.g\.colors_name\s*=\s*['\"]\\K[^'\"]+(?=['\"])" "$NEOVIM_LUA" 2>/dev/null || echo "${THEME_NAME}")
    [ -z "$NVIM_COLORSCHEME" ] && NVIM_COLORSCHEME="${THEME_NAME}"
else
    # Remove old theme plugin if it exists
    rm -f "$LAZYVIM_PLUGINS/cruzalex-theme.lua" 2>/dev/null

    # Check for theme-specific colorscheme mapping file
    COLORSCHEME_FILE="$THEME_DIR/nvim-colorscheme"
    if [ -f "$COLORSCHEME_FILE" ]; then
        NVIM_COLORSCHEME=$(cat "$COLORSCHEME_FILE")
    else
        # Map theme name to common Neovim colorschemes
        case "${THEME_NAME}" in
            tokyo-night*) NVIM_COLORSCHEME="tokyonight" ;;
            gruvbox*) NVIM_COLORSCHEME="gruvbox" ;;
            catppuccin*) NVIM_COLORSCHEME="catppuccin" ;;
            dracula*) NVIM_COLORSCHEME="dracula" ;;
            nord*) NVIM_COLORSCHEME="nord" ;;
            one-dark*|onedark*) NVIM_COLORSCHEME="onedark" ;;
            solarized*) NVIM_COLORSCHEME="solarized" ;;
            cobalt2*) NVIM_COLORSCHEME="cobalt2" ;;
            rose-pine*) NVIM_COLORSCHEME="rose-pine" ;;
            kanagawa*) NVIM_COLORSCHEME="kanagawa" ;;
            everforest*) NVIM_COLORSCHEME="everforest" ;;
            monokai*) NVIM_COLORSCHEME="monokai" ;;
            ayu*) NVIM_COLORSCHEME="ayu" ;;
            *) NVIM_COLORSCHEME="${THEME_NAME}" ;;
        esac
    fi
fi

# Write colorscheme to file - nvim can watch this via autocmd
# This is the non-blocking approach (no socket IPC)
echo "$NVIM_COLORSCHEME" > "$CRUZALEX_DIR/.nvim-colorscheme"

# Also create a lua file that nvim can source on theme change
# This enables live colorscheme switching without restart
mkdir -p "$NVIM_CONFIG/lua/cruzalex"
cat > "$NVIM_CONFIG/lua/cruzalex/theme.lua" << EOF
-- Auto-generated by cruzalex-theme-set
-- This file is updated when themes change
return {
  colorscheme = "$NVIM_COLORSCHEME",
  theme_name = "${THEME_NAME}",
}
EOF

# Try to signal nvim instances via SIGUSR1 (non-blocking)
# This is faster and safer than socket communication
pkill -USR1 nvim 2>/dev/null || true
