#!/bin/bash
# Theme hook: Update ncspot (Spotify TUI) colors

CRUZALEX_DIR="${CRUZALEX_DIR:-$HOME/.config/cruzalex}"
THEME_DIR="${THEME_DIR:-$CRUZALEX_DIR/current}"

# Support both native and flatpak ncspot installations
NCSPOT_CONFIG_DIR="$HOME/.config/ncspot"
NCSPOT_FLATPAK_CONFIG_DIR="$HOME/.var/app/io.github.hrkfdn.ncspot/config/ncspot"

# Get colors from theme
get_colors() {
    local colors_file="$THEME_DIR/colors.toml"
    if [ -f "$colors_file" ]; then
        BG=$(grep '^background' "$colors_file" | head -1 | cut -d'"' -f2)
        FG=$(grep '^foreground' "$colors_file" | head -1 | cut -d'"' -f2)
        ACCENT=$(grep '^accent' "$colors_file" | head -1 | cut -d'"' -f2)
        COLOR1=$(grep '^color1 *=' "$colors_file" | head -1 | cut -d'"' -f2)  # red
        COLOR2=$(grep '^color2 *=' "$colors_file" | head -1 | cut -d'"' -f2)  # green
        COLOR3=$(grep '^color3 *=' "$colors_file" | head -1 | cut -d'"' -f2)  # yellow
        COLOR4=$(grep '^color4 *=' "$colors_file" | head -1 | cut -d'"' -f2)  # blue
        COLOR8=$(grep '^color8 *=' "$colors_file" | head -1 | cut -d'"' -f2)  # bright black
    fi
    # Defaults if not found
    BG="${BG:-#1a1b26}"
    FG="${FG:-#c0caf5}"
    ACCENT="${ACCENT:-#7aa2f7}"
    COLOR1="${COLOR1:-#f7768e}"
    COLOR2="${COLOR2:-#9ece6a}"
    COLOR3="${COLOR3:-#e0af68}"
    COLOR4="${COLOR4:-#7aa2f7}"
    COLOR8="${COLOR8:-#414868}"
}

# Generate ncspot theme to a specific config dir
write_ncspot_theme() {
    local config_dir="$1"
    local theme_file="$config_dir/theme.toml"

    mkdir -p "$config_dir"

    cat > "$theme_file" << EOF
# Auto-generated by cruzalex-theme-set
# Theme: ${THEME_NAME}

[theme]
background = "${BG}"
primary = "${FG}"
secondary = "${COLOR8}"
title = "${ACCENT}"
playing = "${COLOR2}"
playing_selected = "${COLOR2}"
playing_bg = "${BG}"
highlight = "${ACCENT}"
highlight_bg = "${BG}"
error = "${COLOR1}"
error_bg = "${BG}"
statusbar = "${BG}"
statusbar_progress = "${ACCENT}"
statusbar_bg = "${BG}"
cmdline = "${FG}"
cmdline_bg = "${BG}"
search_match = "${COLOR3}"
EOF
}

# Generate ncspot theme for all installations
generate_ncspot_theme() {
    get_colors

    # Write to native config location
    write_ncspot_theme "$NCSPOT_CONFIG_DIR"

    # Write to flatpak config location if it exists or flatpak is installed
    if [ -d "$NCSPOT_FLATPAK_CONFIG_DIR" ] || flatpak list 2>/dev/null | grep -q ncspot; then
        write_ncspot_theme "$NCSPOT_FLATPAK_CONFIG_DIR"
    fi
}

generate_ncspot_theme

# Note: ncspot doesn't support live reload, user needs to restart
