#!/bin/bash
# Theme hook: Update spotify-player theme

CRUZALEX_DIR="${CRUZALEX_DIR:-$HOME/.config/cruzalex}"
THEME_DIR="${THEME_DIR:-$CRUZALEX_DIR/current}"
SPOTIFY_CONFIG="$HOME/.config/spotify-player"

# Link theme if provided
if [ -f "$THEME_DIR/spotify-player/theme.toml" ]; then
    mkdir -p "$SPOTIFY_CONFIG"
    ln -sf "$THEME_DIR/spotify-player/theme.toml" "$SPOTIFY_CONFIG/theme.toml"
    return
fi

# Generate theme from colors.toml
generate_spotify_theme() {
    local colors_file="$THEME_DIR/colors.toml"
    local output_file="$SPOTIFY_CONFIG/theme.toml"

    if [ ! -f "$colors_file" ]; then
        return
    fi

    mkdir -p "$SPOTIFY_CONFIG"

    local bg=$(grep '^background' "$colors_file" | cut -d'"' -f2)
    local fg=$(grep '^foreground' "$colors_file" | cut -d'"' -f2)
    local accent=$(grep '^accent' "$colors_file" | cut -d'"' -f2)

    cat > "$output_file" << EOF
# Auto-generated by cruzalex-theme-set
[theme]
background = "$bg"
foreground = "$fg"
selection = "$accent"
EOF
}

generate_spotify_theme
