#!/bin/bash
# Theme hook: Update spotify-player theme

CRUZALEX_DIR="${CRUZALEX_DIR:-$HOME/.config/cruzalex}"
THEME_DIR="${THEME_DIR:-$CRUZALEX_DIR/current}"
SPOTIFY_CONFIG="$HOME/.config/spotify-player"

# Link theme if provided by the Omarchy theme
if [ -f "$THEME_DIR/spotify-player/theme.toml" ]; then
    mkdir -p "$SPOTIFY_CONFIG"
    ln -sf "$THEME_DIR/spotify-player/theme.toml" "$SPOTIFY_CONFIG/theme.toml"
    exit 0
fi

# Generate theme from colors.toml
generate_spotify_theme() {
    local colors_file="$THEME_DIR/colors.toml"
    local output_file="$SPOTIFY_CONFIG/theme.toml"

    if [ ! -f "$colors_file" ]; then
        return
    fi

    mkdir -p "$SPOTIFY_CONFIG"

    # Parse colors
    local bg=$(grep '^background' "$colors_file" | head -1 | cut -d'"' -f2)
    local fg=$(grep '^foreground' "$colors_file" | head -1 | cut -d'"' -f2)
    local accent=$(grep '^accent' "$colors_file" | head -1 | cut -d'"' -f2)
    local color0=$(grep '^color0 *=' "$colors_file" | head -1 | cut -d'"' -f2)   # black
    local color1=$(grep '^color1 *=' "$colors_file" | head -1 | cut -d'"' -f2)   # red
    local color2=$(grep '^color2 *=' "$colors_file" | head -1 | cut -d'"' -f2)   # green
    local color3=$(grep '^color3 *=' "$colors_file" | head -1 | cut -d'"' -f2)   # yellow
    local color4=$(grep '^color4 *=' "$colors_file" | head -1 | cut -d'"' -f2)   # blue
    local color5=$(grep '^color5 *=' "$colors_file" | head -1 | cut -d'"' -f2)   # magenta
    local color6=$(grep '^color6 *=' "$colors_file" | head -1 | cut -d'"' -f2)   # cyan
    local color8=$(grep '^color8 *=' "$colors_file" | head -1 | cut -d'"' -f2)   # bright black

    # Defaults
    bg="${bg:-#1a1b26}"
    fg="${fg:-#c0caf5}"
    accent="${accent:-#7aa2f7}"
    color0="${color0:-#15161e}"
    color1="${color1:-#f7768e}"
    color2="${color2:-#9ece6a}"
    color3="${color3:-#e0af68}"
    color4="${color4:-#7aa2f7}"
    color5="${color5:-#bb9af7}"
    color6="${color6:-#7dcfff}"
    color8="${color8:-#414868}"

    cat > "$output_file" << EOF
# Auto-generated by cruzalex-theme-set
# Theme: ${THEME_NAME}

[[themes]]
name = "cruzalex"

[themes.palette]
background = "$bg"
foreground = "$fg"
black = "$color0"
red = "$color1"
green = "$color2"
yellow = "$color3"
blue = "$color4"
magenta = "$color5"
cyan = "$color6"
white = "$fg"
bright_black = "$color8"
bright_white = "$fg"
bright_red = "$color1"
bright_green = "$color2"
bright_yellow = "$color3"
bright_blue = "$color4"
bright_magenta = "$color5"
bright_cyan = "$color6"

[themes.component_style]
block_title = { fg = "$accent", modifiers = ["Bold"] }
border = { fg = "$color8" }
playback_track = { fg = "BrightWhite", modifiers = ["Bold"] }
playback_artists = { fg = "$accent" }
playback_album = { fg = "$color8" }
playback_metadata = { fg = "$color8" }
playback_progress_bar = { bg = "$color8", fg = "$accent" }
current_playing = { fg = "$color2", modifiers = ["Bold"] }
page_desc = { fg = "$accent", modifiers = ["Bold"] }
table_header = { fg = "$accent", modifiers = ["Bold"] }
selection = { fg = "$bg", bg = "$accent", modifiers = ["Bold"] }
EOF
}

generate_spotify_theme
