#!/bin/bash
# Theme hook: Update Tmux colors

CRUZALEX_DIR="${CRUZALEX_DIR:-$HOME/.config/cruzalex}"
THEME_DIR="${THEME_DIR:-$CRUZALEX_DIR/current}"
TMUX_CONFIG_DIR="$HOME/.config/tmux"
TMUX_THEME_FILE="$TMUX_CONFIG_DIR/theme.conf"

# Get colors from theme
get_colors() {
    local colors_file="$THEME_DIR/colors.toml"
    if [ -f "$colors_file" ]; then
        BG=$(grep '^background' "$colors_file" | head -1 | cut -d'"' -f2)
        FG=$(grep '^foreground' "$colors_file" | head -1 | cut -d'"' -f2)
        ACCENT=$(grep '^accent' "$colors_file" | head -1 | cut -d'"' -f2)
        COLOR0=$(grep '^color0 *=' "$colors_file" | head -1 | cut -d'"' -f2)
        COLOR8=$(grep '^color8 *=' "$colors_file" | head -1 | cut -d'"' -f2)
    fi
    # Defaults if not found
    BG="${BG:-#1a1b26}"
    FG="${FG:-#c0caf5}"
    ACCENT="${ACCENT:-#7aa2f7}"
    COLOR0="${COLOR0:-#15161e}"
    COLOR8="${COLOR8:-#414868}"
}

# Generate tmux theme config
generate_tmux_theme() {
    get_colors
    mkdir -p "$TMUX_CONFIG_DIR"

    cat > "$TMUX_THEME_FILE" << EOF
# Auto-generated by cruzalex-theme-set
# Theme: ${THEME_NAME}

# Status bar colors
set -g status-style "bg=${BG},fg=${FG}"

# Window status
set -g window-status-style "bg=${BG},fg=${COLOR8}"
set -g window-status-current-style "bg=${ACCENT},fg=${BG},bold"
set -g window-status-activity-style "bg=${BG},fg=${ACCENT}"

# Pane borders
set -g pane-border-style "fg=${COLOR8}"
set -g pane-active-border-style "fg=${ACCENT}"

# Message style
set -g message-style "bg=${ACCENT},fg=${BG}"
set -g message-command-style "bg=${BG},fg=${FG}"

# Mode style (copy mode)
set -g mode-style "bg=${ACCENT},fg=${BG}"

# Clock
set -g clock-mode-colour "${ACCENT}"

# Status bar format
set -g status-left "#[bg=${ACCENT},fg=${BG},bold] #S #[bg=${BG}] "
set -g status-right "#[fg=${FG}] %H:%M #[bg=${ACCENT},fg=${BG},bold] %d-%b "
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
EOF
}

generate_tmux_theme

# Reload tmux if running (non-blocking)
if command -v tmux &>/dev/null && tmux list-sessions &>/dev/null; then
    tmux source-file "$TMUX_THEME_FILE" 2>/dev/null || true
fi
