#!/bin/bash
# Theme hook: Update Yazi file manager theme

CRUZALEX_DIR="${CRUZALEX_DIR:-$HOME/.config/cruzalex}"
THEME_DIR="${THEME_DIR:-$CRUZALEX_DIR/current}"
YAZI_CONFIG="$HOME/.config/yazi"

# Link theme if provided
if [ -d "$THEME_DIR/yazi" ]; then
    mkdir -p "$YAZI_CONFIG"
    if [ -f "$THEME_DIR/yazi/theme.toml" ]; then
        ln -sf "$THEME_DIR/yazi/theme.toml" "$YAZI_CONFIG/theme.toml"
    fi
    return
fi

# Generate minimal theme from colors.toml
generate_yazi_theme() {
    local colors_file="$THEME_DIR/colors.toml"
    local output_file="$YAZI_CONFIG/theme.toml"

    if [ ! -f "$colors_file" ]; then
        return
    fi

    mkdir -p "$YAZI_CONFIG"

    # Yazi uses a complex theme format, so we just set basic colors
    # Full theming would require the theme to provide a complete yazi theme

    local accent=$(grep '^accent' "$colors_file" | cut -d'"' -f2)

    cat > "$output_file" << EOF
# Auto-generated by cruzalex-theme-set
# For full theming, add yazi/theme.toml to your theme

[manager]
cwd = { fg = "$accent" }

[status]
separator_open = ""
separator_close = ""

[select]
border = { fg = "$accent" }
EOF
}

generate_yazi_theme
